name: Template Validation

on:
  push:
    paths:
      - 'src/presentation/templates.py'
      - 'src/presentation/template_validator.py'
      - 'scripts/validate_templates.py'
  pull_request:
    paths:
      - 'src/presentation/templates.py'
      - 'src/presentation/template_validator.py'
      - 'scripts/validate_templates.py'

jobs:
  validate-templates:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install jinja2
    
    - name: Validate Templates
      run: python scripts/validate_templates.py
    
    - name: Run Template Tests
      run: |
        pip install pytest
        pytest tests/test_template_validator.py -v